services:
  ollama:
    image: ollama/ollama
    networks:
      - app-network

  ai-dev-app:
    image: cornellappdev/ai-dev:${IMAGE_TAG}
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - app-network

networks:
  app-network:
