services:
  ollama:
    image: ollama/ollama
    networks:
      - app-network
  
  prepopulate:
    image: cornellappdev/ai-dev:${IMAGE_TAG}
    command: ["npx", "ts-node", "scripts/prepopulateEmails.ts"]
    env_file:
      - .env
    networks:
      - app-network

  ai-dev-app:
    image: cornellappdev/ai-dev:${IMAGE_TAG}
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ollama
      - prepopulate
    networks:
      - app-network

networks:
  app-network:
    #  TODO: Delete
    # driver: overlay
    # attachable: true
