services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    command: ["docker", "exec", "ollama", "ollama", "run", "llama3.2:1b"]

  ai-dev-app:
    image: cornellappdev/ai-dev:${IMAGE_TAG}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - app-network

networks:
  app-network: