services:
  ollama:
    image: ollama/ollama
    networks:
      - app-network

  seeder:
    image: cornellappdev/ai-dev:${IMAGE_TAG}
    command: ["npx", "prisma", "db", "seed"]
    env_file:
      - .env
    volumes:
      - ./ca-certificate.crt:/app/ca-certificate.crt:ro

  ai-dev-app:
    image: cornellappdev/ai-dev:${IMAGE_TAG}
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./ca-certificate.crt:/app/ca-certificate.crt:ro
    depends_on:
      - ollama
      - seeder
    networks:
      - app-network

networks:
  app-network:
