import Providers from "./Providers";
import type { Metadata } from "next";
import "@/globals.css";

// TODO: Add favicon
// TODO: Change font
export const metadata: Metadata = {
  title: "AI Dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* TODO: Add more metadata here */}
      </head>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
